# Generated by Django 6.0.3 on 2026-03-21 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilCandidatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario_expectativa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('experiencia', models.TextField()),
                ('nivel_educacao', models.IntegerField(choices=[(1, 'Ensino fundamental'), (2, 'Ensino medio'), (3, 'Tecnologo'), (4, 'Ensino Superior'), (5, 'Pos / MBA / Mestrado'), (6, 'Doutorado')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidato_perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
