# Generated by Django 6.0.3 on 2026-03-21 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilCandidatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario_expectativa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('experiencia', models.TextField()),
                ('nivel_educacao', models.IntegerField(choices=[(1, 'Ensino fundamental'), (2, 'Ensino médio'), (3, 'Tecnólogo'), (4, 'Ensino Superior'), (5, 'Pós / MBA / Mestrado'), (6, 'Doutorado')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidato_perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('range_salario', models.CharField(choices=[('UP_TO_1000', 'Até 1.000'), ('FROM_1000_TO_2000', 'De 1.000 a 2.000'), ('FROM_2000_TO_3000', 'De 2.000 a 3.000'), ('ABOVE_3000', 'Acima de 3.000')], max_length=30)),
                ('requisitos', models.TextField()),
                ('educacao_minima', models.IntegerField(choices=[(1, 'Ensino fundamental'), (2, 'Ensino médio'), (3, 'Tecnólogo'), (4, 'Ensino Superior'), (5, 'Pós / MBA / Mestrado'), (6, 'Doutorado')])),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabalhos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Aplicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicacoes', to=settings.AUTH_USER_MODEL)),
                ('trabalho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicacoes', to='trabalhos.trabalho')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('candidato', 'trabalho'), name='unique_candidato_trabalho')],
            },
        ),
    ]
