# Generated by Django 6.0.3 on 2026-03-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabalhos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabalho',
            name='educacao_minima',
            field=models.IntegerField(choices=[(1, 'Ensino fundamental'), (2, 'Ensino medio'), (3, 'Tecnologo'), (4, 'Ensino Superior'), (5, 'Pos / MBA / Mestrado'), (6, 'Doutorado')]),
        ),
        migrations.DeleteModel(
            name='PerfilCandidatos',
        ),
    ]
